[package]
name = "slint-league-runes"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
slint = "0.2.0"

[build-dependencies]
slint-build = "0.2.0"
reqwest = { version = "0.11.9", features = ["blocking"] }
toml = "0.5.8"
