[package]
name = "slint-league-runes-ui"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "slint_league_runes_ui"

[dependencies]
slint = "0.2.0"

[build-dependencies]
slint-build = "0.2.0"
