import { Button } from "std-widgets.slint";

export struct Rune := {
  name: string,
  icon: image,
}

export RuneButton := Button {
  property <Rune> rune;
  property <bool> active: false;
  property <string> type: "sub";

  opacity: active ? 1 : 0.5;
  border-width: 0;
  background: transparent;

  states [
    keystone when type == "keystone" : {
      width: 100px;
      height: 100px;
    }
    main when type == "main" : {
      width: 70px;
      height: 70px;
    }
    sub when type == "sub" : {
      width: 50px;
      height: 50px;
    }
  ]

  animate opacity { duration: 200ms; }
  clicked => { self.active = !self.active; }

  Image {
    source: rune.icon;
    width: 100%;
    height: 100%;    
  }
}
