import { Button } from "std-widgets.slint";

export struct Rune := {
  name: string,
  icon: image,
}

export RuneButton := Button {
  property <Rune> rune;
  property <bool> active: false;
  property <string> type: "sub";

  border-width: 0;
  background: transparent;

  states [
    keystone when type == "keystone" : {
      width: 100px;
      height: 100px;
    }
    main when type == "main" : {
      width: 70px;
      height: 70px;
    }
    sub when type == "sub" : {
      width: 50px;
      height: 50px;
    }
  ]
  
  Image {
    source: rune.icon;
    width: 100%;
    height: 100%;
    opacity: active ? 1 : 0.5;
    animate opacity { duration: 200ms; }
  }
  
  TouchArea {
    clicked => { active = !active; }

    HorizontalLayout {
      x: parent.mouse-x - rect.width;
      y: parent.mouse-y - rect.height;
      z: 10;
      visible: parent.has-hover;
      
      rect := Rectangle {
        width: text.width + 20px;
        height: text.height + 20px;
        border-radius: 4px;
        border-width: 1px;
        border-color: blue;
        background: white;
  
        text := Text {
          x: 10px;
          y: 10px;
          text: rune.name;
          font-size: 16px;
        }
      }
    }
  }
}
